export class TrackedEventDto {
  // User identifier
  user: number;

  // Session identifier
  // Generated by the frontend
  session: number;

  // Event date and time
  timestamp: number;

  // URL of the page containing the button
  url: string;
}

export class ButtonEventDto extends TrackedEventDto {
  // Button text
  button_text: string;

  // Button id
  button_id: string;

  // Container name
  container_name: string;
}

// Sent when the user leaves the input field
export class FormFieldEventDto extends TrackedEventDto {
  // Form page name
  form_name: string;

  // Input name
  field_name: string;

  // Input type
  field_type: 'text' | 'checkbox' | 'date' | 'select' | 'other';

  // Is the field required or optional?
  optional: boolean;

  // Seconds taken by the user to fill in the field
  seconds_taken: number;

  // When field_type is text, amount of characters written
  characters_written: number;

  // When field_type is text, amount of characters deleted
  characters_deleted: number;
}

// Sent when the user leaves the input field
export class FormPageEventDto extends TrackedEventDto {
  // Form page name
  form_name: string;

  // Seconds taken by the user to fill in the form
  seconds_taken: number;

  // Amount of fields
  amount_fields: number;

  // Amount of optional fields
  amount_optional_fields: number;

  // Amount of filled fields
  amount_filled_fields: number;
}

export class ScreenEventDto extends TrackedEventDto {
  // Screen name
  screen_name: string;

  // Possible values:
  // 'enter' -> User entered the screen
  // 'leave' -> User closed the screen
  action: 'enter' | 'leave';
}

export class ButtonEventResponseDto extends ButtonEventDto {
  id: number;
}

export class FormFieldEventResponseDto extends FormFieldEventDto {
  id: number;
}

export class FormPageEventResponseDto extends FormPageEventDto {
  id: number;
}

export class ScreenEventResponseDto extends ScreenEventDto {
  id: number;
}
